import { Component, DemandWeek } from "./types";

export const seedBom: Component[] = [
  {
    id: "asic-js-main",
    name: "JetStream NIC ASIC (custom)",
    category: "Silicon",
    supplier: "TSMC",
    region: "Taiwan",
    source: "sole",
    leadTimeWeeks: 22,
    unitCost: 850,
    moq: 100,
    qtyPerNic: 1,
    onHand: 1200,
  },
  {
    id: "retimer-800g",
    name: "800G SerDes Retimer",
    category: "Silicon",
    supplier: "Broadcom",
    region: "USA",
    source: "dual",
    leadTimeWeeks: 16,
    unitCost: 180,
    moq: 250,
    qtyPerNic: 4,
    onHand: 6400,
  },
  {
    id: "pcie-switch-gen5",
    name: "PCIe Gen5 Switch (32 lane)",
    category: "Silicon",
    supplier: "Broadcom",
    region: "USA",
    source: "sole",
    leadTimeWeeks: 14,
    unitCost: 220,
    moq: 200,
    qtyPerNic: 1,
    onHand: 900,
  },
  {
    id: "lpddr5-buffer",
    name: "LPDDR5 16GB (packet buffer)",
    category: "Memory",
    supplier: "SK Hynix",
    region: "South Korea",
    source: "dual",
    leadTimeWeeks: 12,
    unitCost: 95,
    moq: 500,
    qtyPerNic: 2,
    onHand: 3000,
  },
  {
    id: "qsfp-dd-800g",
    name: "QSFP-DD 800G Optical Module",
    category: "Optics",
    supplier: "InnoLight",
    region: "China",
    source: "dual",
    leadTimeWeeks: 18,
    unitCost: 600,
    moq: 100,
    qtyPerNic: 2,
    onHand: 1400,
  },
  {
    id: "vrm-multiphase",
    name: "Multiphase VRM Controller",
    category: "Power",
    supplier: "Monolithic Power Systems",
    region: "Taiwan",
    source: "dual",
    leadTimeWeeks: 10,
    unitCost: 12,
    moq: 1000,
    qtyPerNic: 3,
    onHand: 12000,
  },
  {
    id: "power-stage-70a",
    name: "70A DrMOS Power Stage",
    category: "Power",
    supplier: "Infineon",
    region: "Malaysia",
    source: "multi",
    leadTimeWeeks: 8,
    unitCost: 4,
    moq: 5000,
    qtyPerNic: 12,
    onHand: 48000,
  },
  {
    id: "pcb-16layer-hsd",
    name: "16-Layer High-Speed PCB",
    category: "PCB",
    supplier: "TTM Technologies",
    region: "USA",
    source: "dual",
    leadTimeWeeks: 9,
    unitCost: 85,
    moq: 200,
    qtyPerNic: 1,
    onHand: 700,
  },
  {
    id: "conn-pcie-edge",
    name: "PCIe Edge Connector Gen5",
    category: "Connector",
    supplier: "Amphenol",
    region: "USA",
    source: "dual",
    leadTimeWeeks: 6,
    unitCost: 8,
    moq: 1000,
    qtyPerNic: 1,
    onHand: 4500,
  },
  {
    id: "conn-qsfp-cage",
    name: "QSFP-DD Cage Assembly",
    category: "Connector",
    supplier: "Molex",
    region: "USA",
    source: "dual",
    leadTimeWeeks: 7,
    unitCost: 18,
    moq: 500,
    qtyPerNic: 2,
    onHand: 2800,
  },
  {
    id: "osc-clock-jitter",
    name: "Low-Jitter Clock Oscillator",
    category: "Silicon",
    supplier: "SiTime",
    region: "USA",
    source: "sole",
    leadTimeWeeks: 11,
    unitCost: 6,
    moq: 2000,
    qtyPerNic: 2,
    onHand: 9000,
  },
  {
    id: "bmc-mcu",
    name: "Board Management Controller",
    category: "Silicon",
    supplier: "ASPEED",
    region: "Taiwan",
    source: "sole",
    leadTimeWeeks: 10,
    unitCost: 8,
    moq: 1000,
    qtyPerNic: 1,
    onHand: 3500,
  },
  {
    id: "heatsink-vapor",
    name: "Vapor Chamber Heatsink",
    category: "Mechanical",
    supplier: "Auras Technology",
    region: "Taiwan",
    source: "dual",
    leadTimeWeeks: 8,
    unitCost: 45,
    moq: 200,
    qtyPerNic: 1,
    onHand: 1100,
  },
  {
    id: "passives-mlcc-array",
    name: "MLCC Array (high-grade)",
    category: "Passives",
    supplier: "Murata",
    region: "Japan",
    source: "multi",
    leadTimeWeeks: 6,
    unitCost: 0.15,
    moq: 100000,
    qtyPerNic: 380,
    onHand: 1200000,
  },
];

export const seedDemand: DemandWeek[] = [
  { week: 1, jetstreamUnits: 80 },
  { week: 2, jetstreamUnits: 120 },
  { week: 3, jetstreamUnits: 150 },
  { week: 4, jetstreamUnits: 180 },
  { week: 5, jetstreamUnits: 220 },
  { week: 6, jetstreamUnits: 260 },
  { week: 7, jetstreamUnits: 300 },
  { week: 8, jetstreamUnits: 340 },
  { week: 9, jetstreamUnits: 380 },
  { week: 10, jetstreamUnits: 420 },
  { week: 11, jetstreamUnits: 460 },
  { week: 12, jetstreamUnits: 500 },
];
