import { BomTable } from "@/components/BomTable";
import { KpiStrip } from "@/components/KpiStrip";
import { MrpTimeline } from "@/components/MrpTimeline";
import { RiskHeatmap } from "@/components/RiskHeatmap";
import { ScenarioPanel } from "@/components/ScenarioPanel";
import { AiBriefCard } from "@/components/AiBriefCard";

const ACCENT = "#ef4444";

export default function Home() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <main className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-8">
        <header className="space-y-1 border-b pb-4">
          <h1 className="text-xl font-semibold tracking-tight">
            JetStream Supply Risk &amp; MRP Simulator
          </h1>
          <p className="text-xs" style={{ color: ACCENT }}>
            Representative model. Not d-Matrix proprietary data.
          </p>
        </header>

        <KpiStrip />

        <ScenarioPanel />

        <section className="grid gap-4 lg:grid-cols-3">
          <div className="rounded-lg border p-4 lg:col-span-2">
            <h2 className="mb-3 text-sm font-semibold">MRP timeline</h2>
            <MrpTimeline />
          </div>
          <div className="rounded-lg border p-4">
            <h2 className="mb-3 text-sm font-semibold">Top supplier risk</h2>
            <RiskHeatmap />
          </div>
        </section>

        <section className="rounded-lg border p-4">
          <h2 className="mb-3 text-sm font-semibold">Bill of materials</h2>
          <BomTable />
        </section>

        <AiBriefCard />

        <footer className="mt-4 flex flex-col gap-2 border-t pt-4 text-xs text-muted-foreground">
          <p>
            Representative model based on public product information. Not
            d-Matrix proprietary data. Executive brief generated by Claude
            Sonnet 4.6.
          </p>
          <p>
            <a
              href="https://www.linkedin.com/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline-offset-4 hover:underline"
            >
              LinkedIn
            </a>
          </p>
        </footer>
      </main>
    </div>
  );
}
