"use client";

import { useMemo, useState } from "react";
import { Loader2, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { useStore } from "@/store/useStore";
import { runMrp } from "@/lib/mrp";
import { computeRiskScores } from "@/lib/risk";
import { Component, MrpRow } from "@/lib/types";

interface ShortageDetail {
  componentId: string;
  componentName: string;
  weeks: number[];
  totalUnits: number;
  unitCost: number;
  dollarExposure: number;
}

interface MrpSummary {
  totalShortageWeeks: number;
  totalDollarExposure: number;
  componentsInShortage: ShortageDetail[];
}

export function AiBriefCard() {
  const bom = useStore((s) => s.bom);
  const demand = useStore((s) => s.demand);
  const scenario = useStore((s) => s.scenario);

  const [brief, setBrief] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const payload = useMemo(() => {
    const rows = runMrp(bom, demand, scenario);
    const mrpSummary = buildSummary(rows, bom);
    const topRisks = computeRiskScores(bom).slice(0, 3).map((r) => {
      const c = bom.find((x) => x.id === r.componentId);
      return {
        rank: r.rank,
        componentId: r.componentId,
        componentName: c?.name ?? r.componentId,
        supplier: c?.supplier,
        region: c?.region,
        leadTimeWeeks: c?.leadTimeWeeks,
        source: c?.source,
        composite: round(r.composite),
        leadTimeScore: round(r.leadTimeScore),
        sourceScore: round(r.sourceScore),
        geoScore: round(r.geoScore),
      };
    });
    return { mrpSummary, topRisks, scenario };
  }, [bom, demand, scenario]);

  async function generate() {
    setLoading(true);
    setError(null);
    setBrief(null);
    try {
      const res = await fetch("/api/brief", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = (await res.json()) as { brief?: string; error?: string };
      if (!res.ok || !data.brief) {
        throw new Error(data.error ?? "Failed to generate brief.");
      }
      setBrief(data.brief);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-3 rounded-lg border p-4">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold">Executive brief</h2>
          <p className="text-xs text-muted-foreground">
            Generated by Claude Sonnet 4.6 from the current MRP and risk state.
          </p>
        </div>
        <Button onClick={generate} disabled={loading}>
          {loading ? (
            <Loader2 className="size-3 animate-spin" />
          ) : (
            <Sparkles className="size-3" />
          )}
          {loading ? "Generating" : "Generate executive brief"}
        </Button>
      </div>

      {error && (
        <div className="rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-xs text-destructive">
          {error}
        </div>
      )}

      {brief && (
        <article className="prose prose-sm max-w-none rounded-md border bg-muted/30 p-3 text-sm leading-relaxed dark:prose-invert">
          <ReactMarkdown>{brief}</ReactMarkdown>
        </article>
      )}

      {!brief && !error && !loading && (
        <p className="text-xs text-muted-foreground">
          Click the button to generate a brief from the current plan state.
        </p>
      )}
    </div>
  );
}

function buildSummary(rows: MrpRow[], bom: Component[]): MrpSummary {
  const byId = new Map(bom.map((c) => [c.id, c]));
  const details: ShortageDetail[] = [];
  let totalShortageWeeks = 0;
  let totalDollarExposure = 0;

  for (const row of rows) {
    const comp = byId.get(row.componentId);
    if (!comp) continue;
    const shortageWeeks = row.weeks.filter((w) => w.shortage > 0);
    if (shortageWeeks.length === 0) continue;
    const units = shortageWeeks.reduce((sum, w) => sum + w.shortage, 0);
    const dollars = units * comp.unitCost;
    totalShortageWeeks += shortageWeeks.length;
    totalDollarExposure += dollars;
    details.push({
      componentId: comp.id,
      componentName: comp.name,
      weeks: shortageWeeks.map((w) => w.week),
      totalUnits: units,
      unitCost: comp.unitCost,
      dollarExposure: Math.round(dollars),
    });
  }

  details.sort((a, b) => b.dollarExposure - a.dollarExposure);

  return {
    totalShortageWeeks,
    totalDollarExposure: Math.round(totalDollarExposure),
    componentsInShortage: details,
  };
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}
